Update kernel.yml

diff --git a/.github/workflows/kernel.yml b/.github/workflows/kernel.yml
--- a/.github/workflows/kernel.yml
+++ b/.github/workflows/kernel.yml
@@ -132,9 +132,17 @@ jobs:
             cp ../../susfs4ksu/kernel_patches/fs/* fs/
             cp ../../susfs4ksu/kernel_patches/include/linux/* include/linux/
             patch -p1 < ../../susfs4ksu/kernel_patches/50_add_susfs_in_gki-${{ steps.vars.outputs.android }}-${{ github.event.inputs.kernel_version }}.patch
+
             test -f fs/susfs.c
 
-            grep -R "config KSU_SUSFS" . >/dev/null || echo 'source "fs/Kconfig"' >> fs/Kconfig
+            if ! grep -R "config KSU_SUSFS" fs >/dev/null; then
+              if [ -f fs/Kconfig.susfs ]; then
+                grep -q 'Kconfig.susfs' fs/Kconfig || echo 'source "fs/Kconfig.susfs"' >> fs/Kconfig
+              else
+                echo "missing SUSFS Kconfig"
+                exit 1
+              fi
+            fi
           fi
 
           cd ..
